[project]
name = "mmcp-client"
version = "0.1.0"
description = "Multi MCP Client"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.4.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
